[project]
title = "Laptop Reviews Analysis Project"
version = "0.1.0"
port = 8501
slug = "laptop-reviews-analysis-project-946230"  # Required: Unique identifier for your project
entrypoint = "app.py"    # Required: Main script to run when executing preswald run

[branding]
name = "Laptop Reviews Analysis Project"
logo = "images/laptop-icon-29.png"
favicon = "images/laptop-icon-29.png"
primaryColor = "#F89613"

[data.reviews_csv]
type = "csv"
path = "data/reviews.csv"

[logging]
level = "INFO"  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"